[build]
  command = "yarn build:website"
  publish = "website/build"

[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.19"
  NODE_VERSION = "22"
  NODE_OPTIONS = "--max_old_space_size=8192"
